[[pages]]
path = "app.py"
name = "🏠 Home"
icon = "🏠"

[[pages]]
path = "pages/1_Evaluasi_Model.py"
name = "📈 Evaluasi Model"
icon = "📈"

[[pages]]
path = "pages/2_Prediksi_Status.py"
name = "🤖 Prediksi Status"
icon = "🤖"

[[pages]]
path = "pages/3_Informasi_Penelitian.py"
name = "📖 Informasi Penelitian"
icon = "📖"
